sudo: required
language: ruby
cache: bundler
matrix:
  include:
  - rvm: 2.4.4
    env:
    - DB=mysql
    - CONN_STR='DRIVER=MySQL;SERVER=localhost;DATABASE=odbc_test;USER=root;PASSWORD=;'
    addons:
      apt:
        packages:
        - unixodbc
        - unixodbc-dev
        - libmyodbc
        - mysql-client-5.6
      services:
        - mysql
  - rvm: 2.4.4
    env:
    - DB=postgresql
    - CONN_STR='DRIVER={PostgreSQL ANSI};SERVER=localhost;PORT=5432;DATABASE=odbc_test;UID=postgres;'
    addons:
      postgresql: "9.2"
      apt:
        packages:
        - unixodbc
        - unixodbc-dev
        - odbc-postgresql-09.06
  - rvm: 2.5.1
    env:
    - DB=mysql
    - CONN_STR='DRIVER=MySQL;SERVER=localhost;DATABASE=odbc_test;USER=root;PASSWORD=;'
    addons:
      apt:
        packages:
        - unixodbc
        - unixodbc-dev
        - libmyodbc
        - mysql-client-5.6
      services:
        - mysql
  - rvm: 2.5.1
    env:
    - DB=postgresql
    - CONN_STR='DRIVER={PostgreSQL ANSI};SERVER=localhost;PORT=5432;DATABASE=odbc_test;UID=postgres;'
    addons:
      postgresql: "9.2"
      apt:
        packages:
        - unixodbc
        - unixodbc-dev
        - odbc-postgresql-09.06
before_script: bin/ci-setup
